### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by krishnakanike** [agreatfool/swagger-spec-to-pdf#2]
unable to use swagger2pdf. Any help here is appreciated 

Ubuntu 16.04 LTS 

demouser@SGLinuxVM:~$ node -v
v4.2.6
demouser@SGLinuxVM:~$ npm -v
3.5.2
demouser@SGLinuxVM:~$ 

demouser@SGLinuxVM:/usr/local/bin/node_modules/swagger-spec-to-pdf/bin$./swagger2pdf -s ../swagger-spec-sample.json -o ../dump/events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/bin/node_modules/swagger-spec-to-pdf/node_modules/.bin/http-server ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by agreatfool** [comment]
Previous version: 
``` json
"dependencies": {
  "swagger-spec-to-pdf": "^1.0.3"
}
```
Update with: 
``` shell
npm update swagger-spec-to-pdf
```
New version shall be: `swagger-spec-to-pdf@1.0.4`
And then have a try~

**Comment by dj1703** [comment]
Hello,

I'm having the same problem using the current version 1.0.4 of swagger2pdf. When running your tool I see the following output (using GitBash on a Windows 7 machine):
```
$ ./bin/swagger2pdf -s ./swagger-spec-sample.json -o ./dump/
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files\nodejs\node_modules\http-server\bin\http-server ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I'm using these version of npm and Node:
```
$ npm -v
3.10.10
```
```
$ node -v
v6.9.5
```

Any help would be most welcome.

**Comment by krishnakanike** [comment]
the above update to v1.0.4 did not work for me. So, i used another swagger. 
here you go - https://github.com/simonstewart/swagger-to-PDF

**Comment by dj1703** [comment]
Thank you Scrooge2, the other project works like a charm!

**Comment by zleao** [comment]
I´m running on windows 10 x64. When trying to execute, I have the same 'unhandled error event'
I´ve tried the on ein the link that @Scrooge2 mentioned, but the formatting is comming out wrong and I would like to try other converters to see if there's any difference. Do you have any ideia on how to solve this?
Thanks

$npm -v
v6.9.4

$npm -v
3.10.10

$node swagger2pdf -s ./test.json -o ./
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\perei\AppData\Roaming\npm\node_modules\swagger-spec-to-pdf\node_modules\.bin\http-server ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
