### ISSUE TITLE
throw er; // Unhandled 'error' event (on v1.0.5)

### ISSUE THREAD

**Issue by MJ17** [agreatfool/swagger-spec-to-pdf#4]
Hi, I'm having this error below when trying to run the bin.
even with the sample json file.

Please help.

$ ./bin/swagger2pdf -s swagger-spec-sample.json -o ./dump/
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn D:\8-workspace\iot-dev\git-repo\librarian\node_modules\http-server\bin\http-server ENOENT
    at exports._errnoException (util.js:1014:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

$ ./bin/swagger2pdf -v
1.0.5

$ npm -v
5.0.3

$ node -v
v8.1.0

**Comment by agreatfool** [comment]
Version update: 1.0.7
Please install it as global package: `npm install -g swagger-spec-to-pdf`

```shell
$ node -v
v8.1.0
$ npm -v
5.0.3
$ swagger2pdf -v
1.0.7
```

**Comment by MJ17** [comment]
I updated to v 1.0.7
however error is almost the same.

Please help.

$ swagger2pdf -s my_sample_swagger.json -o ./dump/
events.js:182
throw er; // Unhandled 'error' event
^

Error: spawn  http-server ENOENT
at exports._errnoException (util.js:1014:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
at onErrorNT (internal/child_process.js:366:16)
at _combinedTickCallback (internal/process/next_tick.js:102:11)
at process._tickCallback (internal/process/next_tick.js:161:9)
