### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by arrcher** [agreatfool/swagger-spec-to-pdf#6]
``>swagger2pdf -s api.json -o dump\``

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn http-server ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

`>npm -v`
5.3.0

`>node -v`
v6.11.2

`>swagger2pdf -v`
1.0.7

**Comment by agreatfool** [comment]
Please check this issue: [link](https://github.com/agreatfool/swagger-spec-to-pdf/issues/5). `http-server` issue shall be cannot reproduced anymore since latest version.

**Comment by betsyerickson** [comment]
I am also seeing this error, and yes I have installed http-server and other packages globally.   I am posting the command run from PowerShell on a Windows 7 system but I have tried from the normal command prompt and from several different directories and get the same error:

PS C:\> swagger2pdf -s ./swagger.json -o ./
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn http-server ENOENT
    at _errnoException (util.js:1019:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
PS C:\> npm -v
5.5.1
PS C:\> node -v
v8.6.0
PS C:\> swagger2pdf -v
1.0.7

**Comment by DenisBabarykin** [comment]
I have the same error

**Comment by enochj** [comment]
I got this error as well.

**Comment by odupuy** [comment]
Same issue here

W7 with GitBash
npm 5.6.1
node 9.8.1
http-server 0.11.1 installed locally and globally
swagger-spec-to-pdf 1.0.7

**Comment by o-klp** [comment]
@odupuy @DenisBabarykin @betsyerickson I had the same issue. My fix was to install swagger-spec-to-pdf locally, and use that:
- `cd node_modules/swagger-spec-to-pdf`
- `npm install` (installs http-server local to swagger-spec-to-pdf)
- `bin/swagger2pdf -s ../../swagger.json -o ../../docs` run using local install of swagger-spec-to-pdf and resources at project root

Hope that helps!

**Comment by pmundt** [comment]
I can also confirm that installing http-server relative to the swagger2pdf location fixes this issue. Verified with Ubuntu 18.04 under Windows 10 WSL.
